name: On Push

on:
  push:

jobs:
  test:
    name: flake8-mypy-pytest
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout current project
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.ref_name }}
      - name: Install poetry
        run: pip install poetry
      - name: Install poetry dependencies
        run: poetry install
      - name: Lint
        run: poetry run flake8 .
      - name: Typecheck
        run: poetry run mypy .
      - name: Test
        run: poetry run pytest
