name: On Push to main

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      env:
        GITHUB_SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        envs: GITHUB_SHA
        script: |
          cd ${{ secrets.SSH_PATH }}
          docker build -t api .
          docker run --expose 8080 api
